# Generated by Django 5.1.3 on 2024-11-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.comments'),
        ),
    ]
