# Generated by Django 5.1.3 on 2024-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_posts_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comment',
        ),
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.comments'),
        ),
    ]
